{% set name = "google-cloud-secret-manager" %}
{% set version = "2.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-secret-manager-{{ version }}.tar.gz
  sha256: 9da1357bb4f51343f7331242318737619efdbffdd54d6d7d0ff2e1cd189eee39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - proto-plus >=1.15.0

test:
  imports:
    - google
    - google.cloud
    - google.cloud.secretmanager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-secret-manager
  summary: Secret Manager API API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vladsaveliev
    - xylar
